apiVersion: v1
kind: Pod
metadata:
  name: temp-shell
spec:
  containers:
    - name: temp-shell
      image: busybox
      command: ["sleep", "36000"]  # Keeps the pod running
      volumeMounts:
        - name: secret-volume
          mountPath: /cloudzero/secret
          readOnly: true
  volumes:
    - name: secret-volume
      secret:
        secretName: cloudzero-secret-api-key
    - name: persistent-storage
      mountPath: /cloudzero/data
    
  restartPolicy: Never
