// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -destination=mocks/metrics_client_mock.go -package=mocks -source=interface.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	metricsapi "github.com/cloudzero/cloudzero-agent/operator/internal/metricsapi"
)

// MockMetricsClient is a mock of MetricsClient interface.
type MockMetricsClient struct {
	ctrl     *gomock.Controller
	recorder *MockMetricsClientMockRecorder
}

// MockMetricsClientMockRecorder is the mock recorder for MockMetricsClient.
type MockMetricsClientMockRecorder struct {
	mock *MockMetricsClient
}

// NewMockMetricsClient creates a new mock instance.
func NewMockMetricsClient(ctrl *gomock.Controller) *MockMetricsClient {
	mock := &MockMetricsClient{ctrl: ctrl}
	mock.recorder = &MockMetricsClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricsClient) EXPECT() *MockMetricsClientMockRecorder {
	return m.recorder
}

// GetComponentMemory mocks base method.
func (m *MockMetricsClient) GetComponentMemory(ctx context.Context, namespace string, labelSelector map[string]string, containerName string) (*metricsapi.ComponentMetrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetComponentMemory", ctx, namespace, labelSelector, containerName)
	ret0, _ := ret[0].(*metricsapi.ComponentMetrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetComponentMemory indicates an expected call of GetComponentMemory.
func (mr *MockMetricsClientMockRecorder) GetComponentMemory(ctx, namespace, labelSelector, containerName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetComponentMemory", reflect.TypeOf((*MockMetricsClient)(nil).GetComponentMemory), ctx, namespace, labelSelector, containerName)
}
