apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-agent-ksm
spec:
  selector:
    matchLabels:
      app: prometheus-agent-ksm
  template:
    metadata:
      labels:
        app: prometheus-agent-ksm
    spec:
      serviceAccountName: prometheus-agent-sa
      securityContext:
        fsGroup: 65534
        runAsGroup: 65534
        runAsNonRoot: true
        runAsUser: 65534
      volumes:
        - name: config-volume
          emptyDir: {}
        - name: cloudzero-api-key
          secret:
            secretName: cz-api-token
      initContainers:
        - name: prometheus-configurator
          image: busybox
          command:
            - /bin/sh
            - -c
            - |
              # Log message
              echo "Writing prometheus.yml configuration"

              # Write to prometheus.yml using HEREDOC with proper indentation
              cat <<EOF > /opt/prometheus/prometheus.yml
              global:
                scrape_interval: 30s
              remote_write:
                - url: https://api.cloudzero.com/v1/container-metrics?cluster_name=cloudzero-eks-cluster-eksCluster-45e897d&cloud_account_id=975482786146&region=us-east-2
                  remote_timeout: 30s
                  write_relabel_configs:
                    - source_labels: [__name__]
                      regex: '^(kube_node_info|kube_node_status_capacity|kube_pod_container_resource_limits|kube_pod_container_resource_requests|kube_pod_labels|kube_pod_info|container_cpu_usage_seconds_total|container_memory_working_set_bytes|container_network_receive_bytes_total|container_network_transmit_bytes_total)$'
                      action: keep
                  authorization:
                    type: Bearer
                    credentials_file: /etc/config/prometheus/secrets/value
                  queue_config:
                    capacity: 10000
                    max_shards: 50
                    min_shards: 1
                    max_samples_per_send: 2000
                    batch_send_deadline: 5s
                    min_backoff: 30ms
                    max_backoff: 5s
                  metadata_config:
                    send: false
                    send_interval: 1m
              scrape_configs:
                - job_name: 'kube-state-metrics-node'
                  honor_timestamps: true
                  scrape_interval: 30s
                  scrape_timeout: 10s
                  metrics_path: /metrics
                  scheme: http
                  enable_compression: true
                  follow_redirects: true
                  enable_http2: true
                  relabel_configs:
                    - separator: ;
                      regex: __meta_kubernetes_service_label_(.+)
                      replacement: \$1
                      action: labelmap
                    - source_labels: [__meta_kubernetes_namespace]
                      separator: ;
                      regex: (.*)
                      target_label: namespace
                      replacement: \$1
                      action: replace
                    - source_labels: [__meta_kubernetes_service_name]
                      separator: ;
                      regex: (.*)
                      target_label: service
                      replacement: \$1
                      action: replace
                    - source_labels: [__meta_kubernetes_pod_node_name]
                      separator: ;
                      regex: (.*)
                      target_label: node
                      replacement: \$1
                      action: replace
                  metric_relabel_configs:
                    - source_labels: [__name__]
                      separator: ;
                      regex: '^(kube_node_info|kube_node_status_capacity)$'
                      action: keep
                    - separator: ;
                      regex: '^(board_asset_tag|container|created_by_kind|created_by_name|image|instance|name|namespace|node|node_kubernetes_io_instance_type|pod|product_name|provider_id|resource|unit|uid|_.*|label_.*|app.kubernetes.io/.*|k8s.*)$'
                      action: labelkeep
                  static_configs:
                    - targets:
                        - kube-state-metrics.monitors.svc.cluster.local:8080
                - job_name: 'kube-state-metrics-pods'
                  honor_timestamps: true
                  scrape_interval: 30s
                  scrape_timeout: 10s
                  metrics_path: /metrics
                  scheme: http
                  enable_compression: true
                  follow_redirects: true
                  enable_http2: true
                  relabel_configs:
                    - separator: ;
                      regex: __meta_kubernetes_service_label_(.+)
                      replacement: \$1
                      action: labelmap
                    - source_labels: [__meta_kubernetes_namespace]
                      separator: ;
                      regex: (.*)
                      target_label: namespace
                      replacement: \$1
                      action: replace
                    - source_labels: [__meta_kubernetes_service_name]
                      separator: ;
                      regex: (.*)
                      target_label: service
                      replacement: \$1
                      action: replace
                    - source_labels: [__meta_kubernetes_pod_node_name]
                      separator: ;
                      regex: (.*)
                      target_label: node
                      replacement: \$1
                      action: replace
                  metric_relabel_configs:
                    - source_labels: [__name__]
                      separator: ;
                      regex: '^(kube_pod_container_resource_limits|kube_pod_container_resource_requests|kube_pod_labels|kube_pod_info)$'
                      action: keep
                    - separator: ;
                      regex: '^(board_asset_tag|container|created_by_kind|created_by_name|image|instance|name|namespace|node|node_kubernetes_io_instance_type|pod|product_name|provider_id|resource|unit|uid|_.*|label_.*|app.kubernetes.io/.*|k8s.*)$'
                      action: labelkeep
                  static_configs:
                    - targets:
                        - kube-state-metrics.monitors.svc.cluster.local:8080
              EOF

              # Display the generated configuration
              cat /opt/prometheus/prometheus.yml
          volumeMounts:
            - name: config-volume
              mountPath: /opt/prometheus

      containers:
        - name: prometheus-agent-ksm
          image: quay.io/prometheus/prometheus:v2.50.1
          args:
            - '--config.file=/opt/prometheus/prometheus.yml'
            - '--web.enable-lifecycle'
            - '--web.console.libraries=/etc/prometheus/console_libraries'
            - '--web.console.templates=/etc'
          ports:
            - containerPort: 9090
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /-/ready
              port: 9090
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 4
          volumeMounts:
            - name: config-volume
              mountPath: /opt/prometheus
            - name: cloudzero-api-key
              mountPath: /etc/config/prometheus/secrets/
              readOnly: true
