version: "2"
run:
  concurrency: 4
  issues-exit-code: 2
  tests: false
output:
  path-prefix: ""
linters:
  default: none
  enable:
    - copyloopvar
    - dupl
    - dupword
    - errcheck
    - goconst
    - gocritic
    - goheader
    - gosec
    - govet
    - intrange
    - nilnil
    - nolintlint
    - paralleltest
    - perfsprint
    - prealloc
    - promlinter
    - revive
    - sqlclosecheck
    - staticcheck
    - tagliatelle
    - testifylint
    - tparallel
    - zerologlint
  settings:
    dupl:
      threshold: 100
    errcheck:
      check-type-assertions: true
    goheader:
      template: |-
        SPDX-FileCopyrightText: Copyright (c) 2016-2025, CloudZero, Inc. or its affiliates. All Rights Reserved.
        SPDX-License-Identifier: Apache-2.0
    govet:
      enable:
        - shadow
    nolintlint:
      require-explanation: true
      require-specific: true
    revive:
      rules:
        - name: atomic
        - name: add-constant
          arguments:
            - allowFloats: 0.0,0.,1.0,1.,2.0,2.,3.0,3.
              allowInts: 0,1,2,3,10,8,16,32,64,100,128,192,256,512,1024,2048,4096,8192,16384,32768,65536
              allowStrs: '""'
              maxLitCount: "3"
        - name: atomic
        - name: comment-spacings
        - name: confusing-naming
        - name: confusing-results
        - name: constant-logical-expr
        - name: context-as-argument
        - name: context-keys-type
        - name: datarace
        - name: deep-exit
        - name: exported
          arguments:
            - checkPrivateReceivers
            - disableStutteringCheck
            - checkPublicInterface
            - disableChecksOnFunctions
    tagliatelle:
      case:
        rules:
          yaml: snake
        use-field-name: true
    staticcheck:
      checks:
        - "-QF1001" # Disable De Morgan's law suggestions
        - "-QF1011" # Disable type inference suggestions
    testifylint:
      enable-all: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - goheader
        path: app/types/mocks
    paths:
      - app/types/status/cluster_status.pb.go
      - app/types/mocks
      - mock/
      - tests/
      - third_party$
      - builtin$
      - examples$
issues:
  uniq-by-line: false
formatters:
  enable:
    - gofumpt
  exclusions:
    generated: lax
    paths:
      - app/types/status/cluster_status.pb.go
      - app/types/mocks
      - mock/
      - tests/
      - third_party$
      - builtin$
      - examples$
