run:
  concurrency: 4
  timeout: 5m
  issues-exit-code: 2
  tests: false
  skip-dirs:
    - pkg/status
    - .go
    - .git

output:
  print-issued-lines: false
  print-linter-name: true
  uniq-by-line: false
  path-prefix: ""
  sort-results: true

linters:
  disable-all: true

  enable:
    # bugs/error
    - staticcheck
    - revive
    - govet
    - errcheck
    - gosec
    - dupl

    # performance
    - gocritic
    - prealloc

    # style, formatting
    - stylecheck
    - goconst
    - gofmt
    - goheader
    - tagliatelle

linters-settings:
  errcheck:
    # Report about not checking of errors in type assertions: `a := b.(MyStruct)`.
    # Such cases aren't reported by default.
    # Default: false
    check-type-assertions: true
  gofmt:
    # Apply the rewrite rules to the source before reformatting.
    # https://pkg.go.dev/cmd/gofmt
    # Default: []
    rewrite-rules:
      - pattern: "interface{}"
        replacement: "any"
      - pattern: "a[b:len(a)]"
        replacement: "a[b:]"
  goheader:
    template: |-
      SPDX-FileCopyrightText: Copyright (c) 2016-2024, CloudZero, Inc. or its affiliates. All Rights Reserved.
      SPDX-License-Identifier: Apache-2.0
  dupl:
    # Tokens count to trigger issue, Default: 150
    threshold: 100
  tagliatelle:
    case:
      use-field-name: true
      rules:
        # Any struct tag type can be used.
        # Support string case: `camel`, `pascal`, `kebab`, `snake`, `upperSnake`, `goCamel`, `goPascal`, `goKebab`, `goSnake`, `upper`, `lower`, `header`.
        yaml: snake
