{{- $values := include "cloudzero-agent.values" . | fromYaml -}}
{{ if $values.insightsController.tls.useCertManager }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "cloudzero-agent.issuerName" . }}
  namespace: {{ .Release.Namespace }}
  {{- include "cloudzero-agent.generateLabels" (dict "globals" . "labels" $values.commonMetaLabels) | nindent 2 }}
  {{- include "cloudzero-agent.generateAnnotations" $values.defaults.annotations | nindent 2 }}
spec:
  {{- if $values.insightsController.tls.issuerSpec }}
  {{- toYaml $values.insightsController.tls.issuerSpec | nindent 2 }}
  {{- else }}
  selfSigned: {}
  {{- end }}
{{- end }}
