apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm.fullname" . }}
  namespace: {{ .Release.Namespace }}
data:
  config.yml: |-
    organization_id: "{{ .Values.cloudZero.organizationId }}"
    cloud_account_id: "{{ .Values.csp.accountId }}"
    region: "{{ .Values.csp.region }}"
    cluster_name: "{{ .Values.clusterName }}"

    server:
      mode: http

    logging:
      level: debug

    database:
      storage_path: /cloudzero/data
      max_records: 1000000
      compress: true

    cloudzero:
      api_key_path: /cloudzero/secret/apiToken
      send_interval: 1m
      send_timeout: 10s
      rotate_interval: 30m
      host: dev-api.cloudzero.com
