{{- $values := include "cloudzero-agent.values" . | fromYaml -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config-values
  namespace: {{ .Release.Namespace }}
  {{- include "cloudzero-agent.generateLabels" (dict "globals" . "labels" $values.commonMetaLabels) | nindent 2 }}
  {{- include "cloudzero-agent.generateAnnotations" $values.defaults.annotations | nindent 2 }}
data:
  values.yaml: |-
{{- merge (dict "apiKey" (ternary "***" nil (not (empty $values.apiKey)))) $values | toYaml | nindent 4 -}}
