{{- if .Values.initCertJob.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "cloudzero-agent.insightsController.labels" . | nindent 4 }}
  {{- include "cloudzero-agent.generateAnnotations" (mergeOverwrite
      (.Values.defaults.annotations | default (dict))
      (dict "checkov.io/skip1" "CKV_K8S_155=This ClusterRole is necessary for the init cert job to update webhook configurations with the CA bundle")
    ) | nindent 2 }}
  name: {{ include "cloudzero-agent.initCertJob.clusterRoleName" . }}
  namespace: {{ include "cloudzero-agent.namespace" . }}
rules:
  - apiGroups:
      - "apps"
    resources:
      - "deployments"
    resourceNames:
      - {{ include "cloudzero-agent.insightsController.deploymentName" . }}
    verbs:
      - "get"
      - "list"
  - apiGroups:
      - ""
    resources:
      - "secrets"
    resourceNames:
      - {{ include "cloudzero-agent.tlsSecretName" . }}
    verbs:
      - get
      - list
      - patch
  - apiGroups:
      - "admissionregistration.k8s.io"
    resources:
      - "validatingwebhookconfigurations"
    resourceNames:
      - {{ include "cloudzero-agent.validatingWebhookConfigName" $ }}
    verbs:
      - get
      - list
      - patch
{{- end }}
