apiVersion: v1
kind: Service
metadata:
  name: {{ include "cloudzero-agent.serviceName" . }}
  labels:
    {{- include "cloudzero-agent.insightsController.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.insightsController.service.port }}
      targetPort: 8443
      name: http
  selector:
    {{- include "cloudzero-agent.insightsController.server.matchLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "cloudzero-agent.aggregator.name" . }}
  labels:
    {{- include "cloudzero-agent.aggregator.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "cloudzero-agent.aggregator.matchLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.aggregator.collector.port }}
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "cloudzero-agent.server.fullname" . }}
  labels:
    {{- include "cloudzero-agent.server.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "cloudzero-agent.server.matchLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
      name: metrics