apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "helm.fullname" . }}
  labels:
    app: collector
spec:
  selector:
    app: collector
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
