{{- $values := include "cloudzero-agent.values" . | fromYaml -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cloudzero-agent.serviceName" . }}
  labels:
    {{- include "cloudzero-agent.insightsController.labels" . | nindent 4 }}
  {{- include "cloudzero-agent.generateAnnotations" $values.defaults.annotations | nindent 2 }}
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - port: {{ $values.insightsController.service.port }}
      targetPort: 8443
      name: http
  selector:
    {{- include "cloudzero-agent.insightsController.server.matchLabels" . | nindent 4 }}
