{{- $values := include "cloudzero-agent.values" . | fromYaml -}}
{{- if $values.insightsController.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cloudzero-agent.insightsController.deploymentName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cloudzero-agent.insightsController.labels" . | nindent 4 }}
  {{- include "cloudzero-agent.generateAnnotations" (merge $values.defaults.annotations $values.insightsController.server.deploymentAnnotations) | nindent 2 }}
spec:
  replicas: {{ $values.insightsController.server.replicaCount | default $values.components.webhookServer.replicas }}
  selector:
    matchLabels:
      {{- include "cloudzero-agent.insightsController.server.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cloudzero-agent.insightsController.labels" . | nindent 8 }}
        {{- with $values.insightsController.server.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- include "cloudzero-agent.generateAnnotations" (merge $values.defaults.annotations $values.insightsController.server.podAnnotations (dict "checksum/config" (include "cloudzero-agent.insightsController.configuration" . | sha256sum))) | nindent 6 }}
    spec:
      serviceAccountName: {{ include "cloudzero-agent.serviceAccountName" . }}
      {{- include "cloudzero-agent.insightsController.server.imagePullSecrets" . | nindent 6 }}
      securityContext:
        runAsUser: 65534
        runAsNonRoot: true
        runAsGroup: 65534
        fsGroup: 65534
      {{ $podAntiAffinity := dict "podAntiAffinity" (dict "preferredDuringSchedulingIgnoredDuringExecution" (list (dict "weight" 100 "podAffinityTerm" (dict "labelSelector" (dict "matchLabels" (dict "app" "webhook-server")) "topologyKey" "kubernetes.io/hostname")))) }}
      {{- $userAffinity := deepCopy $values.insightsController.server.affinity }}
      {{- include "cloudzero-agent.generateAffinity" (dict "default" $values.defaults.affinity "affinity" (merge $userAffinity $podAntiAffinity)) | nindent 6 }}
      {{- include "cloudzero-agent.generateDNSInfo" (dict "defaults" $values.defaults.dns) | nindent 6 }}
      {{- include "cloudzero-agent.generatePriorityClassName" $values.defaults.priorityClassName | nindent 6 }}
      {{- include "cloudzero-agent.generateNodeSelector" (dict "default" $values.defaults.nodeSelector "nodeSelector" $values.insightsController.server.nodeSelector) | nindent 6 }}
      {{- include "cloudzero-agent.generateTolerations" (concat $values.defaults.tolerations $values.insightsController.server.tolerations) | nindent 6 }}
      containers:
        - name: webhook-server
          {{- include "cloudzero-agent.generateImage" (dict "defaults" $values.defaults.image "image" $values.components.agent.image "compat" $values.insightsController.server.image) | nindent 10 }}
          command:
            - /app/cloudzero-webhook
          args:
            - -config
            - "{{ include "cloudzero-agent.insightsController.configurationMountPath" . }}/server-config.yaml"
          ports:
            - containerPort: 8443
          resources:
            {{- toYaml $values.insightsController.resources | nindent 12 }}
          volumeMounts:
            - name: insights-server-config
              mountPath: {{ include "cloudzero-agent.insightsController.configurationMountPath" . }}
          {{- if or $values.insightsController.volumeMounts $values.insightsController.tls.enabled }}
            {{- if $values.insightsController.tls.enabled }}
            - name: tls-certs
              mountPath: {{ $values.insightsController.tls.mountPath }}
              readOnly: true
            {{- end }}
          {{- if or $values.existingSecretName $values.apiKey }}
            - name: cloudzero-api-key
              mountPath: {{ $values.serverConfig.containerSecretFilePath }}
              subPath: ""
              readOnly: true
          {{- end }}
            {{- with $values.insightsController.volumeMounts }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}
          {{- if and $values.insightsController.server.healthCheck.enabled }}
          livenessProbe:
            httpGet:
              scheme: HTTPS
              path: {{ $values.insightsController.server.healthCheck.path }}
              port: {{ $values.insightsController.server.healthCheck.port }}
            initialDelaySeconds: {{ $values.insightsController.server.healthCheck.initialDelaySeconds }}
            periodSeconds: {{ $values.insightsController.server.healthCheck.periodSeconds }}
            timeoutSeconds: {{ $values.insightsController.server.healthCheck.timeoutSeconds }}
            successThreshold: {{ $values.insightsController.server.healthCheck.successThreshold }}
            failureThreshold: {{ $values.insightsController.server.healthCheck.failureThreshold }}
          readinessProbe:
            httpGet:
              scheme: HTTPS
              path: {{ $values.insightsController.server.healthCheck.path }}
              port: {{ $values.insightsController.server.healthCheck.port }}
            initialDelaySeconds: {{ $values.insightsController.server.healthCheck.initialDelaySeconds }}
            periodSeconds: {{ $values.insightsController.server.healthCheck.periodSeconds }}
            timeoutSeconds: {{ $values.insightsController.server.healthCheck.timeoutSeconds }}
            successThreshold: {{ $values.insightsController.server.healthCheck.successThreshold }}
            failureThreshold: {{ $values.insightsController.server.healthCheck.failureThreshold }}
          {{- end }}
      {{- if or $values.insightsController.volumes $values.insightsController.tls.enabled }}
      volumes:
        - name: insights-server-config
          configMap:
            name: {{ include "cloudzero-agent.webhookConfigMapName" . }}
        {{- if $values.insightsController.tls.enabled }}
        - name: tls-certs
          secret:
            secretName: {{ include "cloudzero-agent.tlsSecretName" . }}
        {{- end }}
        {{- if or $values.existingSecretName $values.apiKey }}
        - name: cloudzero-api-key
          secret:
            secretName: {{ include "cloudzero-agent.secretName" . }}
        {{- end }}
        {{- with $values.insightsController.volumes }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
{{- end }}
