name: Smoke Tests

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  smoke-tests:
    runs-on: ubuntu-latest

    # references local file ".secrets"
    env:
      CLOUDZERO_DEV_API_KEY: ${{ secrets.CLOUDZERO_DEV_API_KEY }}
      CLOUDZERO_HOST: dev-api.cloudzero.com
      CLOUD_ACCOUNT_ID: "12345"
      CSP_REGION: "us-east-1"
      CLUSTER_NAME: "insights-controller-integration-test"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Install dependencies
        run: go mod tidy

      # smoke tests hit alfa.
      - name: Run smoke tests
        run: sudo -E make test-smoke
