//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudZeroAgent) DeepCopyInto(out *CloudZeroAgent) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudZeroAgent.
func (in *CloudZeroAgent) DeepCopy() *CloudZeroAgent {
	if in == nil {
		return nil
	}
	out := new(CloudZeroAgent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CloudZeroAgent) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudZeroAgentList) DeepCopyInto(out *CloudZeroAgentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CloudZeroAgent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudZeroAgentList.
func (in *CloudZeroAgentList) DeepCopy() *CloudZeroAgentList {
	if in == nil {
		return nil
	}
	out := new(CloudZeroAgentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CloudZeroAgentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudZeroAgentSpec) DeepCopyInto(out *CloudZeroAgentSpec) {
	*out = *in
	out.TLS = in.TLS
	if in.ResourceManagement != nil {
		in, out := &in.ResourceManagement, &out.ResourceManagement
		*out = new(ResourceManagementSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudZeroAgentSpec.
func (in *CloudZeroAgentSpec) DeepCopy() *CloudZeroAgentSpec {
	if in == nil {
		return nil
	}
	out := new(CloudZeroAgentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudZeroAgentStatus) DeepCopyInto(out *CloudZeroAgentStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ComponentMemory != nil {
		in, out := &in.ComponentMemory, &out.ComponentMemory
		*out = make([]ComponentMemoryStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudZeroAgentStatus.
func (in *CloudZeroAgentStatus) DeepCopy() *CloudZeroAgentStatus {
	if in == nil {
		return nil
	}
	out := new(CloudZeroAgentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComponentMemoryStatus) DeepCopyInto(out *ComponentMemoryStatus) {
	*out = *in
	if in.LastPatchedAt != nil {
		in, out := &in.LastPatchedAt, &out.LastPatchedAt
		*out = (*in).DeepCopy()
	}
	in.LastObservedAt.DeepCopyInto(&out.LastObservedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentMemoryStatus.
func (in *ComponentMemoryStatus) DeepCopy() *ComponentMemoryStatus {
	if in == nil {
		return nil
	}
	out := new(ComponentMemoryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComponentResourceSpec) DeepCopyInto(out *ComponentResourceSpec) {
	*out = *in
	out.Memory = in.Memory
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentResourceSpec.
func (in *ComponentResourceSpec) DeepCopy() *ComponentResourceSpec {
	if in == nil {
		return nil
	}
	out := new(ComponentResourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MemoryBounds) DeepCopyInto(out *MemoryBounds) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MemoryBounds.
func (in *MemoryBounds) DeepCopy() *MemoryBounds {
	if in == nil {
		return nil
	}
	out := new(MemoryBounds)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceManagementSpec) DeepCopyInto(out *ResourceManagementSpec) {
	*out = *in
	if in.Components != nil {
		in, out := &in.Components, &out.Components
		*out = make(map[ComponentName]ComponentResourceSpec, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceManagementSpec.
func (in *ResourceManagementSpec) DeepCopy() *ResourceManagementSpec {
	if in == nil {
		return nil
	}
	out := new(ResourceManagementSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TLSSpec) DeepCopyInto(out *TLSSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TLSSpec.
func (in *TLSSpec) DeepCopy() *TLSSpec {
	if in == nil {
		return nil
	}
	out := new(TLSSpec)
	in.DeepCopyInto(out)
	return out
}
