// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/cloudzero/cloudzero-agent/app/domain/k8s (interfaces: CertificateClient)
//
// Generated by this command:
//
//	mockgen -destination=app/domain/k8s/mocks/certificate_client_mock.go -package=mocks github.com/cloudzero/cloudzero-agent/app/domain/k8s CertificateClient
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	certificate "github.com/cloudzero/cloudzero-agent/app/domain/certificate"
	gomock "go.uber.org/mock/gomock"
)

// MockCertificateClient is a mock of CertificateClient interface.
type MockCertificateClient struct {
	ctrl     *gomock.Controller
	recorder *MockCertificateClientMockRecorder
	isgomock struct{}
}

// MockCertificateClientMockRecorder is the mock recorder for MockCertificateClient.
type MockCertificateClientMockRecorder struct {
	mock *MockCertificateClient
}

// NewMockCertificateClient creates a new mock instance.
func NewMockCertificateClient(ctrl *gomock.Controller) *MockCertificateClient {
	mock := &MockCertificateClient{ctrl: ctrl}
	mock.recorder = &MockCertificateClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCertificateClient) EXPECT() *MockCertificateClientMockRecorder {
	return m.recorder
}

// GetTLSSecret mocks base method.
func (m *MockCertificateClient) GetTLSSecret(ctx context.Context, namespace, secretName string) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTLSSecret", ctx, namespace, secretName)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTLSSecret indicates an expected call of GetTLSSecret.
func (mr *MockCertificateClientMockRecorder) GetTLSSecret(ctx, namespace, secretName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTLSSecret", reflect.TypeOf((*MockCertificateClient)(nil).GetTLSSecret), ctx, namespace, secretName)
}

// GetWebhookCABundle mocks base method.
func (m *MockCertificateClient) GetWebhookCABundle(ctx context.Context, webhookName string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWebhookCABundle", ctx, webhookName)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWebhookCABundle indicates an expected call of GetWebhookCABundle.
func (mr *MockCertificateClientMockRecorder) GetWebhookCABundle(ctx, webhookName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWebhookCABundle", reflect.TypeOf((*MockCertificateClient)(nil).GetWebhookCABundle), ctx, webhookName)
}

// PatchSecret mocks base method.
func (m *MockCertificateClient) PatchSecret(ctx context.Context, namespace, secretName string, patchData map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PatchSecret", ctx, namespace, secretName, patchData)
	ret0, _ := ret[0].(error)
	return ret0
}

// PatchSecret indicates an expected call of PatchSecret.
func (mr *MockCertificateClientMockRecorder) PatchSecret(ctx, namespace, secretName, patchData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PatchSecret", reflect.TypeOf((*MockCertificateClient)(nil).PatchSecret), ctx, namespace, secretName, patchData)
}

// PatchWebhookConfiguration mocks base method.
func (m *MockCertificateClient) PatchWebhookConfiguration(ctx context.Context, webhookName string, patches []certificate.WebhookPatch) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PatchWebhookConfiguration", ctx, webhookName, patches)
	ret0, _ := ret[0].(error)
	return ret0
}

// PatchWebhookConfiguration indicates an expected call of PatchWebhookConfiguration.
func (mr *MockCertificateClientMockRecorder) PatchWebhookConfiguration(ctx, webhookName, patches any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PatchWebhookConfiguration", reflect.TypeOf((*MockCertificateClient)(nil).PatchWebhookConfiguration), ctx, webhookName, patches)
}
