apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: aws-cirrus-jb-cluster
  region: us-east-2

iam:
  withOIDC: true

addons:
  - name: vpc-cni
    version: latest
  - name: kube-proxy
    version: latest
  - name: coredns
    version: latest

nodeGroups:
  - name: ng-1
    instanceType: t3.small
    desiredCapacity: 2
    volumeSize: 20
    amiFamily: Bottlerocket
