// SPDX-FileCopyrightText: Copyright (c) 2016-2025, CloudZero, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

// Package clusterconfig provides protobuf-based cluster configuration management for the CloudZero Agent.
// This package contains generated types and utilities for handling cluster configuration data
// that is serialized using Protocol Buffers for efficient storage and network transmission.
//
// The cluster configuration includes essential settings for:
//   - CloudZero Agent deployment parameters and feature flags
//   - Kubernetes cluster identification and authentication details
//   - Cost allocation policies and tag validation rules
//   - Integration settings for CloudZero platform connectivity
//   - Monitoring and diagnostic configuration options
//
// Configuration data is typically:
//   - Generated by the CloudZero platform and transmitted to agents
//   - Stored locally for offline operation during network interruptions
//   - Validated during agent startup and configuration changes
//   - Updated dynamically through configuration management APIs
//
// The protobuf format enables efficient serialization for configuration distribution
// across multiple agent instances and ensures backward compatibility during platform updates.
package clusterconfig
