// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: clusterconfig.proto

package clusterconfig

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClusterConfig struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	Account                   string                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Region                    string                 `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	Namespace                 string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	ProviderId                string                 `protobuf:"bytes,4,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	ClusterName               string                 `protobuf:"bytes,5,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	K8SVersion                string                 `protobuf:"bytes,6,opt,name=k8s_version,json=k8sVersion,proto3" json:"k8s_version,omitempty"`
	ReleaseName               string                 `protobuf:"bytes,7,opt,name=release_name,json=releaseName,proto3" json:"release_name,omitempty"`
	ChartVersion              string                 `protobuf:"bytes,8,opt,name=chart_version,json=chartVersion,proto3" json:"chart_version,omitempty"`
	AgentVersion              string                 `protobuf:"bytes,9,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	ConfigValuesBase64        string                 `protobuf:"bytes,30,opt,name=config_values_base64,json=configValuesBase64,proto3" json:"config_values_base64,omitempty"`
	ConfigValidatorBase64     string                 `protobuf:"bytes,31,opt,name=config_validator_base64,json=configValidatorBase64,proto3" json:"config_validator_base64,omitempty"`
	ConfigWebhookServerBase64 string                 `protobuf:"bytes,32,opt,name=config_webhook_server_base64,json=configWebhookServerBase64,proto3" json:"config_webhook_server_base64,omitempty"`
	ConfigAggregatorBase64    string                 `protobuf:"bytes,33,opt,name=config_aggregator_base64,json=configAggregatorBase64,proto3" json:"config_aggregator_base64,omitempty"`
	Errors                    []string               `protobuf:"bytes,40,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *ClusterConfig) Reset() {
	*x = ClusterConfig{}
	mi := &file_clusterconfig_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterConfig) ProtoMessage() {}

func (x *ClusterConfig) ProtoReflect() protoreflect.Message {
	mi := &file_clusterconfig_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterConfig.ProtoReflect.Descriptor instead.
func (*ClusterConfig) Descriptor() ([]byte, []int) {
	return file_clusterconfig_proto_rawDescGZIP(), []int{0}
}

func (x *ClusterConfig) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *ClusterConfig) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *ClusterConfig) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ClusterConfig) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *ClusterConfig) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

func (x *ClusterConfig) GetK8SVersion() string {
	if x != nil {
		return x.K8SVersion
	}
	return ""
}

func (x *ClusterConfig) GetReleaseName() string {
	if x != nil {
		return x.ReleaseName
	}
	return ""
}

func (x *ClusterConfig) GetChartVersion() string {
	if x != nil {
		return x.ChartVersion
	}
	return ""
}

func (x *ClusterConfig) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *ClusterConfig) GetConfigValuesBase64() string {
	if x != nil {
		return x.ConfigValuesBase64
	}
	return ""
}

func (x *ClusterConfig) GetConfigValidatorBase64() string {
	if x != nil {
		return x.ConfigValidatorBase64
	}
	return ""
}

func (x *ClusterConfig) GetConfigWebhookServerBase64() string {
	if x != nil {
		return x.ConfigWebhookServerBase64
	}
	return ""
}

func (x *ClusterConfig) GetConfigAggregatorBase64() string {
	if x != nil {
		return x.ConfigAggregatorBase64
	}
	return ""
}

func (x *ClusterConfig) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

var File_clusterconfig_proto protoreflect.FileDescriptor

const file_clusterconfig_proto_rawDesc = "" +
	"\n" +
	"\x13clusterconfig.proto\x12\x06status\"\xae\x04\n" +
	"\rClusterConfig\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\tR\aaccount\x12\x16\n" +
	"\x06region\x18\x02 \x01(\tR\x06region\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12\x1f\n" +
	"\vprovider_id\x18\x04 \x01(\tR\n" +
	"providerId\x12!\n" +
	"\fcluster_name\x18\x05 \x01(\tR\vclusterName\x12\x1f\n" +
	"\vk8s_version\x18\x06 \x01(\tR\n" +
	"k8sVersion\x12!\n" +
	"\frelease_name\x18\a \x01(\tR\vreleaseName\x12#\n" +
	"\rchart_version\x18\b \x01(\tR\fchartVersion\x12#\n" +
	"\ragent_version\x18\t \x01(\tR\fagentVersion\x120\n" +
	"\x14config_values_base64\x18\x1e \x01(\tR\x12configValuesBase64\x126\n" +
	"\x17config_validator_base64\x18\x1f \x01(\tR\x15configValidatorBase64\x12?\n" +
	"\x1cconfig_webhook_server_base64\x18  \x01(\tR\x19configWebhookServerBase64\x128\n" +
	"\x18config_aggregator_base64\x18! \x01(\tR\x16configAggregatorBase64\x12\x16\n" +
	"\x06errors\x18( \x03(\tR\x06errorsB\x12Z\x10../clusterconfigb\x06proto3"

var (
	file_clusterconfig_proto_rawDescOnce sync.Once
	file_clusterconfig_proto_rawDescData []byte
)

func file_clusterconfig_proto_rawDescGZIP() []byte {
	file_clusterconfig_proto_rawDescOnce.Do(func() {
		file_clusterconfig_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_clusterconfig_proto_rawDesc), len(file_clusterconfig_proto_rawDesc)))
	})
	return file_clusterconfig_proto_rawDescData
}

var file_clusterconfig_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_clusterconfig_proto_goTypes = []any{
	(*ClusterConfig)(nil), // 0: status.ClusterConfig
}
var file_clusterconfig_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_clusterconfig_proto_init() }
func file_clusterconfig_proto_init() {
	if File_clusterconfig_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_clusterconfig_proto_rawDesc), len(file_clusterconfig_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_clusterconfig_proto_goTypes,
		DependencyIndexes: file_clusterconfig_proto_depIdxs,
		MessageInfos:      file_clusterconfig_proto_msgTypes,
	}.Build()
	File_clusterconfig_proto = out.File
	file_clusterconfig_proto_goTypes = nil
	file_clusterconfig_proto_depIdxs = nil
}
