// Code generated by MockGen. DO NOT EDIT.
// Source: internal/certmanager/interface.go
//
// Generated by this command:
//
//	mockgen -destination=internal/certmanager/mocks/cert_manager_mock.go -package=mocks -source=internal/certmanager/interface.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	certificate "github.com/cloudzero/cloudzero-agent/app/domain/certificate"
	gomock "go.uber.org/mock/gomock"
)

// MockCertManager is a mock of CertManager interface.
type MockCertManager struct {
	ctrl     *gomock.Controller
	recorder *MockCertManagerMockRecorder
	isgomock struct{}
}

// MockCertManagerMockRecorder is the mock recorder for MockCertManager.
type MockCertManagerMockRecorder struct {
	mock *MockCertManager
}

// NewMockCertManager creates a new mock instance.
func NewMockCertManager(ctrl *gomock.Controller) *MockCertManager {
	mock := &MockCertManager{ctrl: ctrl}
	mock.recorder = &MockCertManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCertManager) EXPECT() *MockCertManagerMockRecorder {
	return m.recorder
}

// Generate mocks base method.
func (m *MockCertManager) Generate(ctx context.Context, serviceName, namespace string, keySize int, validity time.Duration, algorithm string) (*certificate.CertificateData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Generate", ctx, serviceName, namespace, keySize, validity, algorithm)
	ret0, _ := ret[0].(*certificate.CertificateData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Generate indicates an expected call of Generate.
func (mr *MockCertManagerMockRecorder) Generate(ctx, serviceName, namespace, keySize, validity, algorithm any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Generate", reflect.TypeOf((*MockCertManager)(nil).Generate), ctx, serviceName, namespace, keySize, validity, algorithm)
}

// UpdateResources mocks base method.
func (m *MockCertManager) UpdateResources(ctx context.Context, namespace, secretName, webhookName string, certData *certificate.CertificateData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateResources", ctx, namespace, secretName, webhookName, certData)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateResources indicates an expected call of UpdateResources.
func (mr *MockCertManagerMockRecorder) UpdateResources(ctx, namespace, secretName, webhookName, certData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateResources", reflect.TypeOf((*MockCertManager)(nil).UpdateResources), ctx, namespace, secretName, webhookName, certData)
}

// ValidateExisting mocks base method.
func (m *MockCertManager) ValidateExisting(ctx context.Context, namespace, secretName string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateExisting", ctx, namespace, secretName)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateExisting indicates an expected call of ValidateExisting.
func (mr *MockCertManagerMockRecorder) ValidateExisting(ctx, namespace, secretName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateExisting", reflect.TypeOf((*MockCertManager)(nil).ValidateExisting), ctx, namespace, secretName)
}

// ValidateExpiry mocks base method.
func (m *MockCertManager) ValidateExpiry(ctx context.Context, namespace, secretName string, threshold time.Duration) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateExpiry", ctx, namespace, secretName, threshold)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateExpiry indicates an expected call of ValidateExpiry.
func (mr *MockCertManagerMockRecorder) ValidateExpiry(ctx, namespace, secretName, threshold any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateExpiry", reflect.TypeOf((*MockCertManager)(nil).ValidateExpiry), ctx, namespace, secretName, threshold)
}
