apiVersion: v1
kind: Pod
metadata:
  name: temp-shell
  namespace: cirrus
spec:
  containers:
    - name: temp-shell
      image: busybox
      command: ["sleep", "36000"]  # Keeps the pod running
      volumeMounts:
        - name: secret-volume
          mountPath: /cloudzero/secret
          readOnly: true
        - name: config-volume
          mountPath: /cloudzero/config
          readOnly: true
        - name: persistent-storage
          mountPath: /cloudzero/data
  volumes:
    - name: config-volume
      configMap:
        name: cloudzero-collector-config
    - name: secret-volume
      secret:
        secretName: cloudzero-secret
    - name: persistent-storage
      persistentVolumeClaim:
        claimName: database-pvc
  restartPolicy: Never
