apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-pvc
  namespace: cirrus
spec:
  accessModes:
    #- ReadWriteMany
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: local-path
