apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "insights-controller.labels" . | nindent 4 }}
  name: {{ include "insights-controller.configMapName" . }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.server.configMap.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  server-config.yaml: |-
    cloud_account_id: {{ .Values.cloudAccountId }}
    region: {{ .Values.region }}
    cluster_name: {{ .Values.clusterName }}
    host: {{ .Values.host }}
    {{- with .Values.server.tls }}
    remote_write:
      send_interval: 60s
      max_bytes_per_send: 10000000
      send_timeout: 10s
    certificate:
      key: {{ .mountPath }}/tls.key
      cert: {{ .mountPath }}/tls.crt
    {{- end }}
    api_key_path: {{ .Values.server.serverConfig.containerSecretFilePath }}/{{ .Values.server.serverConfig.containerSecretFileName }}
    server:
      port: {{ .Values.server.serverConfig.port }}
      read_timeout: {{ .Values.server.serverConfig.read_timeout }}
      write_timeout: {{ .Values.server.serverConfig.write_timeout }}
      idle_timeout: {{ .Values.server.serverConfig.idle_timeout }}
    filters:
      {{- .Values.server.serverConfig.filters | toYaml | nindent 6 }}
