# -- CloudZero host to send metrics to.
host: api.cloudzero.com
# -- Account ID of the account the cluster is running in. This must be a string - even if it is a number in your system.
cloudAccountId: null
# -- Name of the clusters.
clusterName: null
# -- Region the cluster is running in.
region: null

# -- CloudZero API key. Required if existingSecretName is null.
apiKey: null
# -- If set, the agent will use the API key in this Secret to authenticate with CloudZero.
existingSecretName: null

# Due to limitations of Helm, we are unfortunately not able to automatically configure the
# kube-state-metrics subchart using the configuration above, and instead need to configure
# it here, often duplicating things.
#
# For full documentation on configuring this subchart, see:
# https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-state-metrics
# Specifically, the values.yaml file in that repository:
# https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-state-metrics/values.yaml
kubeStateMetrics:
  enabled: true
  affinity: {}
  tolerations: []
  customLabels: {}
  dnsPolicy: ClusterFirst
  dnsConfig: {}
  annotations: {}
  podAnnotations: {}
  nodeSelector: {}
  podDisruptionBudget:
    minAvailable: 1
  image:
    registry: registry.k8s.io
    repository: kube-state-metrics/kube-state-metrics
    tag: "v2.10.1"
    sha:
    pullPolicy: IfNotPresent
  imagePullSecrets: []
  nameOverride: "cloudzero-state-metrics"
  # Disable CloudZero KSM as a Scrape Target since the service endpoint is
  # explicitly defined by the Validators config file.
  prometheusScrape: false
  # Set a default port other than 8080 to avoid collisions with any existing KSM
  # services.
  service:
    port: 8080
