apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "insights-controller.labels" . | nindent 4 }}
  name: {{ .Release.Name}}-certificates
  namespace: {{ .Release.Namespace }}
  {{- with .Values.secretAnnotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  {{ include "insights-controller.generate-certs" . | nindent 2 }}