apiVersion: v1
kind: Service
metadata:
  name: {{ include "insights-controller.serviceName" . }}
  labels:
    {{- include "insights-controller.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8443
  selector:
    {{- include "insights-controller.selectorLabels" . | nindent 4 }}
