versions:
  chart_version: { { .ChartVerson } }
  agent_version: { { .AgentVersion } }

logging:
  level: info
  location: ./cloudzero-agent-validator.log

deployment:
  account_id: { { .AccountID } }
  cluster_name: { { .ClusterName } }
  region: { { .Region } }
  webhook_server_address: { { .WebhookServerAddress } }

cloudzero:
  host: { { .CloudzeroHost } }
  credentials_file: /etc/config/prometheus/secrets/value

prometheus:
  kube_state_metrics_service_endpoint: { { .KubeStateMetricsURL } }
  configurations:
    - /etc/config/prometheus/configmaps/prometheus.yml

diagnostics:
  stages:
    - name: pre-start
      enforce: true
      checks:
        - egress_reachable
        - api_key_valid
        - webhook_server_reachable
    - name: post-start
      enforce: true
      checks:
        - k8s_version
        - kube_state_metrics_reachable
        - scrape_cfg
    - name: pre-stop
      enforce: false
      checks:
