name: GoModTidy

on: [push]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Golang
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
          cache-dependency-path: go.sum
      - name: Run go mod tidy
        run: go mod tidy
      - name: Check for differences
        run: git diff --exit-code --color
