name: Integration Tests

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    # references local file ".secrets"
    env:
      CLOUDZERO_DEV_API_KEY: ${{ secrets.CLOUDZERO_DEV_API_KEY }}
      CLOUDZERO_HOST: dev-api.cloudzero.com
      CLOUD_ACCOUNT_ID: "12345"
      CSP_REGION: "us-east-1"
      CLUSTER_NAME: "insights-controller-integration-test"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.4

      - name: Print environment variables
        run: env

      - name: Install dependencies
        run: go mod tidy

        # TODO: Currently the only real integration test is TestRemoteWrite.
        # There's an issue with some of the other Tests running in a Linux container,
        # so the command only runs the single test for now.
      - name: Run integration tests
        run: go test -tags=integration -run ^TestRemoteWrite$ ./...
