name: terraform apply (int infra)

on:
  # Not doing this automatically yet.
  #pull_request:
  workflow_dispatch:

jobs:
  run_tests:
    runs-on: ubuntu-latest
    name: Standup integration environment
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use branch workspace
        uses: dflook/terraform-new-workspace@v1
        with:
          path: terraform/aws-eks-cluster
          workspace: ${{ github.head_ref }}

      - name: Deploy test infrastrucutre
        uses: dflook/terraform-apply@v1
        id: test-infra
        with:
          path: terraform/aws-eks-cluster
          workspace: ${{ github.head_ref }}
          auto_approve: true

      # We could run tests, or whatever here if we wanted to.
      #- name: Run tests
      #  run: |
      #    ./run-tests.sh --endpoint "${{ steps.test-infra.outputs.url }}"
