name: terraform apply

on:
  # Since we only have ephemeral resources at the moment,
  # we don't need to currently run this automatically.
  #push:
  #  branches:
  #    - develop
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  apply:
    runs-on: ubuntu-latest
    name: Apply terraform plan
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: terraform apply
        uses: dflook/terraform-apply@v1
        with:
          path: terraform/aws-eks-cluster
